name: Build and Push Docker Image

on:
  push:
    branches:
      - main # Trigger the workflow on pushes to the main branch
    tags:
      - "v*" # Trigger the workflow on new tags

jobs:
  build:

    runs-on: gha-web-app
    # runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract version from tag or set default
        id: version
        run: |
          if [ "${{ github.ref_type }}" == "tag" ]; then
            echo "VERSION=${{ github.ref_name }}" >> $GITHUB_ENV
          else
            COMMIT_SHA=$(echo $GITHUB_SHA | cut -c1-7)
            echo "VERSION=${{ github.run_number }}-${COMMIT_SHA}" >> $GITHUB_ENV
          fi

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/school-scheduler:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/school-scheduler:${{ env.VERSION }}

      - name: Post build cleanup
        run: docker system prune -f
